name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [16, 18, 20]

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true # Garante que os submódulos sejam buscados

      # Set up Node.js environment
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run tests
      - name: Run tests
        run: npm test

      # Lint the code (opcional, mas recomendado)
      - name: Run linter
        run: npm run lint

      # Build (opcional, caso sua aplicação tenha um processo de build)
      - name: Build application
        run: npm run build
        if: runner.os == 'Linux' # Exemplo para rodar build apenas em Linux
